name: aerophoto360
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3dfd8'
    - '#000000'
    - '#304566'
    - '#bba58f'
    - '#64605b'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
